from .roles import roles_bp
from .auth import auth_bp
from .usuarios import usuarios_bp
from .fuentes import fuentes_bp
from .reglas import reglas_bp
from .tipos_eventos import tipos_eventos_bp
from .eventos import eventos_bp
from .alertas import alertas_bp
from .incidentes import incidentes_bp
from .dashboard import dashboard_bp
from .auditoria import auditoria_bp
from app.routes.web import web_bp